version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5226:5226"
    depends_on:
      sqlserver:
        condition: service_healthy
    volumes:
      - .:/app:z
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CleanArchMvc;User=sa;Password=YourStrong!Passw0rd
      - DOTNET_USE_POLLING_FILE_WATCHER=true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  sqlserverdata:
